calendar_diary/urls.py
from django.urls import path
from . import views

app_name = "cal"
urlpatterns = [
    path("", views.index, name="index"),
    path("sc/list/", views.get_event_list, name="get_event_list"),
    path("sc/save/", views.save_event, name="save_event"),
    path("sc/get/<int:id>/", views.get_event, name="get_event"),
    path("sc/delete/", views.delete_event, name="delete_event"),
]

calendarproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include("calendar_diary.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calendar_diary/models.py
from django.db import models
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill


class Event(models.Model):
    start_date = models.DateTimeField('開始日時')
    end_date = models.DateTimeField('終了日時')
    event_name = models.CharField('タイトル', max_length=200)
    is_allday = models.BooleanField('終日？', default=True)
    event_type = models.CharField('タイプ', max_length=40, blank=True)
    description = models.TextField('詳細', blank=True)

    def __str__(self):
        return self.event_name

class Image(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images',blank=True, null=True)
    thumbnail = ImageSpecField(source='image',
                            processors=[ResizeToFill(250,250)],
                            format="JPEG",
                            options={'quality': 60}
                            )

    def __str__(self):
        return self.event.event_name

calendar_diary/forms.py
from django import forms
from .models import Event

# イベントの種別の選択肢
event_type_choices = (
    ('event', 'イベント'),
    ('diary', '日記'),
    ('image', '画像'),
)

# イベントのフォーム
class EventForm(forms.Form):
    # イベントのID
    event_id = forms.IntegerField(
        required=True,
        initial="0",
        widget=forms.HiddenInput
    )
    # イベントのタイプ
    event_type = forms.fields.ChoiceField(
        required=True,
        initial='event',
        choices = event_type_choices,
        widget=forms.RadioSelect,
        label=''
    )
    event_name = forms.CharField(
        required=True, max_length=80, label='表題')
    is_allday = forms.BooleanField(
        required=False, initial=False, label='終日')
    start_date = forms.DateTimeField(
        required=True,
        label='開始日時',
        widget = forms.DateTimeInput(attrs={'type': 'datetime-local'})
    )
    end_date = forms.DateTimeField(
        required=True,
        label='終了日時',
        widget = forms.DateTimeInput(attrs={'type': 'datetime-local'})
    )
    description = forms.CharField(
        required=False, widget=forms.Textarea(), label='記事')
    image = forms.ImageField(required=False, label='画像')


# イベントリストのリクエストのときのバリデーション用
class CalendarForm(forms.Form):
    start_date = forms.DateTimeField(required=True)
    end_date = forms.DateTimeField(required=True)

# 削除のリクエストのときのバリデーション用
class DeleteForm(forms.Form):
    event_id = forms.IntegerField(required=True)

calendar_diary/views.py
import json
import time
from django.http import Http404
from django.template import loader
from django.http import HttpResponse, JsonResponse
from django.middleware.csrf import get_token
from django.shortcuts import render
from django.forms.models import model_to_dict

from .base64decode import decode_base64_file, is_image
from .models import Event, Image
from .forms import CalendarForm, EventForm, DeleteForm

# Create your views here.

def index(request):
    """
    カレンダー画面
    """
    # CSRFのトークンを発行する
    get_token(request)

    # データを初期値としてフォームをレンダリング
    context = {
        'form': EventForm(),
    }
    return render(request, 'index.html', context)


def save_event(request):
    """
    イベント登録
    """

    if not request.method == "POST":
        # POSTメソッド以外はエラー
        return HttpResponse("リクエストが不正です。",
                            status=404)

    # JSONの解析
    data = json.loads(request.body)
    # バリデーション
    eventForm = EventForm(data)
    if not eventForm.is_valid():
        return HttpResponse("渡されたデータが不正です。",
                            status=400)
    
    data['event_id'] = int(data['event_id'])
    if data['event_id']==0:
        # IDが０なら新規登録
        event, image = createEvent(data)

    else:
        # IDが０でなければ、データ更新
        try:
            event, image = updateEvent(data)
        except Event.DoesNotExist:
            return HttpResponse("渡されたデータが不正です。",
                                status=400)
        # imageが作られていれば、イベントの子のimageを削除
        # 一対一にする。
        if image is not None:
            for a_image in event.image_set.all():
                a_image.image.delete()
                a_image.delete()

    event.save()
    if image is not None:
        image.event = event
        image.save()

    to_json = event_to_dict(event)
    # イベントデータを返す
    return JsonResponse(to_json, safe=False)


def createEvent(data):
    """
    イベントオブジェクトの生成
    """
    event = Event(
        event_type=data['event_type'],
        event_name=data['event_name'],
        start_date=data['start_date'],
        end_date=data['end_date'],
        is_allday = data['is_allday'],
        description = data['description'],
    )
    # Imageも作成して返す
    return event, createImage(data)


def updateEvent(data):
    # イベントデータを取得
    event = Event.objects.get(pk=data['event_id'])
    # データを更新
    event.event_type=data['event_type']
    event.event_name=data['event_name']
    event.start_date=data['start_date']
    event.end_date=data['end_date']
    event.is_allday = data['is_allday']
    event.description = data['description']
    
    return event, createImage(data)


def createImage(data):
    """
    画像オブジェクトの生成
    """
    if not 'image' in data.keys():
        return None
    if  data['image']=='':
        return None
    
    image_data = decode_base64_file(data['image'])
    # バリデーション
    if not is_image(image_data):
        raise HttpResponse("渡されたデータが不正です。",
                            status=400)
    # imageの生成
    image = Image( image = image_data)

    return image


def event_to_dict(event):
    """イベントを辞書に変換する。
    """
    # 辞書に変換
    dct_event = model_to_dict(event)
    # キーidを、event_idに置き換える
    dct_event['event_id'] = dct_event['id']
    del dct_event['id']
    images = event.image_set.all()
    if len(images)>0:
        dct_event['image_url'] = images[0].image.url
        dct_event['thumbnail_url'] = images[0].thumbnail.url

    return dct_event


def get_event_list(request):
    """
    任意の期間内の複数のイベントの取得
    """
    if request.method != "POST":
        # POSTメソッド以外はエラー
        return HttpResponse("リクエストが不正です。",
                            status=404)

    # JSONの解析
    data = json.loads(request.body)
    # バリデーション
    calendarForm = CalendarForm(data)
    if calendarForm.is_valid() == False:
        return HttpResponse("渡されたデータが不正です。",
                            status=400)

    # 指定時間内のイベントを検索
    events = Event.objects.filter(
        start_date__lt=data['end_date'], end_date__gt=data['start_date']
    )
    # 配列を作成
    list = []
    for event in events:
        dct_event = event_to_dict(event)
        list.append(dct_event)

    # 作成した配列をJSONで返す
    return JsonResponse(list, safe=False)


def get_event(request, id):
    """
    イベントの取得
    """
    # URLのIDにてイベントデータを取得
    try:
        event = Event.objects.get(pk=id)
    except Event.DoesNotExist:
        raise Http404("イベントがありません。")
    
    # JSONのイベントデータを返す
    dct_event = event_to_dict(event)
    return JsonResponse(dct_event, safe=False)


def delete_event(request):
    """
    イベントの削除
    """
    if request.method != "POST":
        # POSTメソッド以外はエラー
        return HttpResponse("リクエストが不正です。",
                            status=404)

    # JSONの解析
    data = json.loads(request.body)
    # バリデーション
    deleteForm = DeleteForm(data)
    if deleteForm.is_valid() == False:
        return HttpResponse("渡されたデータが不正です。",
                            status=400)

    # イベントデータを取得
    try:
        event = Event.objects.get(pk=data['event_id'])
    except Event.DoesNotExist:
        raise Http404("イベントがありません。")

    # イベントを削除
    event.delete()
    return HttpResponse()

calendar_diary/templates/event_form_inputs.html
{{ form.event_id }}
{{ form.event_type }}
<p>
    <label for="id_event_name">{{ form.event_name.label }}</label>
    {{ form.event_name }}
</p>
<div class="date_inputs">
    <div class="with_time">
        <p class="with-checkbox">
            {{ form.is_allday }}
            <label for="id_is_allday">{{ form.is_allday.label }}</label>
        </p>
        <div class="if_not_allday">
            <div class="time_date_input">
                <label for="id_start_date">{{ form.start_date.label }}</label>
                {{ form.start_date }}
            </div>
            <div class="time_date_input">
                <label for="id_end_date">{{ form.end_date.label }}</label>
                {{ form.end_date }}
            </div>
        </div>
    </div>
</div>
<p>
    <label for="id_description">{{ form.description.label }}</label>
    {{ form.description }}
</p>
<p>
    <label for="id_image">{{ form.image.label }}</label>
    {{ form.image }}
</p>
<div id="id_image_area">
    <image id="image_preview" />
</div>

calendar_diary/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset='utf-8' />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Icons" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.10.2/main.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" ></script>
    <script src="{% static 'js/app.js' %}"></script>
    <title>Calendar Diary</title>
</head>
<body>
    <div id='calendar'></div>
    <div id="popup-screen" class="back-screen">
        <div class="popup">
            <div class="popup-header">
                <div class="to-edit">
                    <input id="id-check-to-edit" name="check-to-edit" type="checkbox" />
                    <label for="id-check-to-edit">編集</label>
                    <span class="to-delete">
                        <input id="id-check-to-delete" name="check-to-delete" type="checkbox" />
                        <label for="id-check-to-delete">削除</label>
                        <button id="button-delete">削除</button>
                    </span>
                </div>
                <div>
                    <button id="close-popup">×</button>
                </div>
            </div>
            <div class="popup-body">
                <form id="id_post_event_form" action="POST" class="post_event_form" action="">
                    {% csrf_token %}
                    {% include 'event_form_inputs.html' %}
                    <p>
                        <button id="event-submit">送信</button>
                    </p>
                </form>
            </div>
        </div>
    </div>
</body>
</html>